name: "Check Status"
description: "Checks that a website is up and responding correctly"
author: "Timothy Clark"
branding:
  icon: "activity"
  color: "blue"

inputs:
  site-url:
    description: "The site URL to check"
    required: true
  wordpress:
    description: "Whether to check for WordPress-specific errors"
    required: false
    default: false


runs:
  using: "node20"
  main: "dist/index.js"
  env:
    SITE_URL: ${{ inputs.site-url }}
    IS_WORDPRESS: ${{ inputs.wordpress }}
