name: "Check Status"
description: "Checks that a website is up and responding correctly"
author: "Timothy Clark"
branding:
  icon: "activity"
  color: "blue"

inputs:
  site-url:
    description: "The site URL to check"
    required: true
  wordpress:
    description: "Whether to check for WordPress-specific errors"
    required: false
    default: false


runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        working-directory: ${{ github.action_path }}

    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --no-fund --progress=false
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Check if website is up
      env:
        SITE_URL: ${{ inputs.site-url }}
        IS_WORDPRESS: ${{ inputs.wordpress }}
      run: ${{ github.action_path }}/checkStatus.ts
      shell: bash
